#!/bin/bash
set -euo pipefail

# Generate Sources/PRSieve/BuildInfo.swift with current git hash + build date.
# Called by run.sh and release.sh.

cd "$(dirname "$0")/.."

GIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
DIRTY=""
if ! git diff --quiet --ignore-submodules 2>/dev/null || \
   ! git diff --quiet --ignore-submodules --cached 2>/dev/null; then
    # Ignore modifications to BuildInfo.swift itself (self-modification loop)
    CHANGED=$(git status --porcelain | awk '{print $2}' | grep -v '^Sources/PRSieve/BuildInfo.swift$' || true)
    if [ -n "$CHANGED" ]; then
        DIRTY="-dirty"
    fi
fi
BUILD_DATE=$(date -u +"%Y-%m-%d %H:%M UTC")

cat > Sources/PRSieve/BuildInfo.swift <<EOF
// Auto-generated by scripts/generate_build_info.sh. Do not edit.
enum BuildInfo {
    static let gitHash = "${GIT_HASH}${DIRTY}"
    static let buildDate = "${BUILD_DATE}"
}
EOF
